azure:
  activedirectory:
    b2c:
      tenant: ${your-tenant-name}
  <<<<<<< release/2.3.2
      oidc-enabled: true
      client-id: ${your-client-id}
      client-secret: ${your-client-secret}
      reply-url: ${your-reply-url-from-aad} # should be absolute url.
      logout-success-url: ${you-logout-success-url}
      user-flows:
        sign-up-or-sign-in: ${your-sign-up-or-in-user-flow}
        profile-edit: ${your-profile-edit-user-flow}     # optional
        password-reset: ${your-password-reset-user-flow} # optional
  =======
      client-id: ${your-application-id}
      policies:
        sign-up-or-sign-in: # Required
          name: ${your-policy-name}
          reply-url: ${your-policy-reply-url}
        password-reset:     # Optional
          name: ${your-policy-name}
          reply-url: ${your-policy-reply-url}
        profile-edit:       # Optional
          name: ${your-policy-name}
          reply-url: ${your-policy-reply-url}

      # Only absolute URL is supported in following configuration
      logout-success-url: ${your-logout-success-url}            # Required
      password-reset-url: ${your-url-to-process-password-reset} # Optional
      profile-edit-url: ${your-url-to-process-profile-edit}     # Optional

  >>>>>>> aad-b2c-integration
